In [70]:
import numpy as np
import math
import cv2

In [71]:
angle_z = 0
angle_y = 0
angle_x = 0
R_z = np.array([[math.cos(math.radians(angle_z)), -math.sin(math.radians(angle_z)), 0],
                    [math.sin(math.radians(angle_z)), math.cos(math.radians(angle_z)), 0],
                    [0, 0, 1]])
R_y = np.array([[math.cos(math.radians(angle_y)), 0, math.sin(math.radians(angle_y))],
                    [0, 1, 0],
                    [-math.sin(math.radians(angle_y)), 0, math.cos(math.radians(angle_y))]])
R_x = np.array([[1, 0, 0],
                    [0, math.cos(math.radians(angle_x)), -math.sin(math.radians(angle_x))],
                    [0, math.sin(math.radians(angle_x)), math.cos(math.radians(angle_x))]])
rotation_L = R_z @ R_y @ R_x
rotation_L

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
angle_z = 0
angle_y = 0
angle_x = 0
R_z = np.array([[math.cos(math.radians(angle_z)), -math.sin(math.radians(angle_z)), 0],
                    [math.sin(math.radians(angle_z)), math.cos(math.radians(angle_z)), 0],
                    [0, 0, 1]])
R_y = np.array([[math.cos(math.radians(angle_y)), 0, math.sin(math.radians(angle_y))],
                    [0, 1, 0],
                    [-math.sin(math.radians(angle_y)), 0, math.cos(math.radians(angle_y))]])
R_x = np.array([[1, 0, 0],
                    [0, math.cos(math.radians(angle_x)), -math.sin(math.radians(angle_x))],
                    [0, math.sin(math.radians(angle_x)), math.cos(math.radians(angle_x))]])
rotation_R = R_z @ R_y @ R_x
rotation_R

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
positionOfCam_L = np.array([[-0.5],
                            [0],
                            [5]])
temp_0 = -np.matmul(np.transpose(rotation_L), positionOfCam_L)
temp_0

array([[ 0.5],
       [-0. ],
       [-5. ]])

In [74]:
temp_1 = np.concatenate((np.transpose(rotation_L), temp_0), axis=1)
temp_1

array([[ 1. ,  0. ,  0. ,  0.5],
       [ 0. ,  1. ,  0. , -0. ],
       [ 0. ,  0. ,  1. , -5. ]])

In [75]:
transformation_L = np.concatenate((temp_1, np.array([[0, 0, 0, 1]])), axis=0)
transformation_L


array([[ 1. ,  0. ,  0. ,  0.5],
       [ 0. ,  1. ,  0. , -0. ],
       [ 0. ,  0. ,  1. , -5. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [76]:
positionOfCam_R = np.array([[0.5],
                            [0],
                            [5]])
temp_0R = -np.matmul(np.transpose(rotation_R), positionOfCam_R)
temp_0R

array([[-0.5],
       [-0. ],
       [-5. ]])

In [77]:
temp_1R = np.concatenate((np.transpose(rotation_R), temp_0R), axis=1)
temp_1R

array([[ 1. ,  0. ,  0. , -0.5],
       [ 0. ,  1. ,  0. , -0. ],
       [ 0. ,  0. ,  1. , -5. ]])

In [78]:
transformation_R = np.concatenate((temp_1R, np.array([[0, 0, 0, 1]])), axis=0)
transformation_R

array([[ 1. ,  0. ,  0. , -0.5],
       [ 0. ,  1. ,  0. , -0. ],
       [ 0. ,  0. ,  1. , -5. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [79]:
focal_length = 0.03
scaling_factor = 7934.75
width = 1920
height = 1080
K = np.array([[(- focal_length * scaling_factor), 0, (width / 2), 0],
                  [0, (focal_length * scaling_factor), (height / 2), 0],
                  [0, 0, 1, 0],
                  [0, 0, 0, 1]])
K

array([[-238.0425,    0.    ,  960.    ,    0.    ],
       [   0.    ,  238.0425,  540.    ,    0.    ],
       [   0.    ,    0.    ,    1.    ,    0.    ],
       [   0.    ,    0.    ,    0.    ,    1.    ]])

In [80]:
H_L = np.matmul(K, transformation_L)
H_L = np.linalg.inv(H_L)
H_L

array([[-4.20093051e-03, -0.00000000e+00,  4.03289329e+00,
        -5.00000000e-01],
       [ 0.00000000e+00,  4.20093051e-03, -2.26850247e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         5.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [81]:
H_R = np.matmul(K, transformation_R)
H_R = np.linalg.inv(H_R)
H_R

array([[-4.20093051e-03, -0.00000000e+00,  4.03289329e+00,
         5.00000000e-01],
       [ 0.00000000e+00,  4.20093051e-03, -2.26850247e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         5.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [82]:
H_L1 = np.concatenate((H_L[0:2, 0:3], H_L[3, 0:3].reshape(1, 3)), axis=0)
H_L1


array([[-0.00420093, -0.        ,  4.03289329],
       [ 0.        ,  0.00420093, -2.26850247],
       [ 0.        ,  0.        ,  0.        ]])

In [83]:
h_L4 = np.array([[H_L[0, 3]],
                         [H_L[1, 3]],
                         [H_L[3, 3]]])
h_L4


array([[-0.5],
       [ 0. ],
       [ 1. ]])

In [84]:
h_L3 = H_L[2, 0:3] / H_L[2, 3]
h_L3


array([0. , 0. , 0.2])

In [85]:
h_L3 = h_L3.reshape(3, 1)
H_L_rebuilt = np.matmul(np.concatenate((H_L1, h_L4), axis=1),
                                np.concatenate((np.eye(3), -np.transpose(h_L3)), axis=0))
H_L_rebuilt


array([[-0.00420093,  0.        ,  4.13289329],
       [ 0.        ,  0.00420093, -2.26850247],
       [ 0.        ,  0.        , -0.2       ]])

In [86]:
H_R1 = np.concatenate((H_L[0:2, 0:3], H_L[3, 0:3].reshape(1, 3)), axis=0)
h_R4 = np.array([[H_R[0, 3]],
                         [H_R[1, 3]],
                         [H_R[3, 3]]])
h_R3 = H_R[2, 0:3] / H_R[2, 3]
h_R3 = h_R3.reshape(3, 1)
H_R_rebuilt = np.matmul(np.concatenate((H_R1, h_R4), axis=1),
                        np.concatenate((np.eye(3), -np.transpose(h_R3)), axis=0))
H_R_rebuilt

array([[-0.00420093,  0.        ,  3.93289329],
       [ 0.        ,  0.00420093, -2.26850247],
       [ 0.        ,  0.        , -0.2       ]])

In [87]:
H_R_to_L = np.matmul(np.linalg.inv(H_L_rebuilt), H_R_rebuilt)
H_R_to_L

array([[1.00000000e+00, 0.00000000e+00, 4.76085000e+01],
       [0.00000000e+00, 1.00000000e+00, 2.99760217e-14],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

But the result is not correct. I use it to warp image. And the result is in the home file.(I want to show it here, unfortunately failed)