In [2]:
import numpy as np
import Homography_calculation_without_original as hc

In [10]:
rotation_L = hc.rotation_matrix(0.764, 0.487, 0.227, 0.356)
rotation_L

array([[ 5.73036e-01, -3.97544e-01,  7.15752e-01],
       [ 8.18744e-01,  2.77548e-01, -5.01336e-01],
       [ 6.48000e-04,  8.73864e-01,  4.84844e-01]])

In [11]:
rotation_R = hc.rotation_matrix(0.764, 0.450, 0.234, 0.398)
rotation_R

array([[ 5.73036e-01, -3.97544e-01,  7.15752e-01],
       [ 8.18744e-01,  2.77548e-01, -5.01336e-01],
       [ 6.48000e-04,  8.73864e-01,  4.84844e-01]])

In [5]:
c_r = np.array([[8.3214],
                [-6.617],
                [5]])
c_l = np.array([[8],
                [-7],
                [5]])
K, K_small = hc.calibration_matrix(0.03, 99740, 2304, 1536)
K_small

array([[-2.9922e+03,  0.0000e+00,  1.1515e+03],
       [ 0.0000e+00,  2.9922e+03,  7.6750e+02],
       [ 0.0000e+00,  0.0000e+00,  1.0000e+00]])

K_small means calibration matrix and dimension is 3*3

In [12]:
e = K_small @ rotation_L.T @ (c_r - c_l)
e

array([[-1.49496543e+03],
       [ 2.96868412e-01],
       [-1.79056000e-04]])

In [9]:
n_brickwall = hc.normal_vector_of_plane(0.5, 0.5, 0.5, 0.5)
n_brickwall

array([[1.],
       [0.],
       [0.]])

n_brickwall means the normal vector of plane

In [13]:
H_infty = K_small @ rotation_L.T @ np.linalg.inv(rotation_R.T) @ np.linalg.inv(K_small)
H_infty

array([[ 1.02642542e+00,  1.67338365e-02, -2.78607757e+02],
       [-1.74207640e-02,  9.78764611e-01,  2.47754599e+02],
       [ 2.65019906e-05, -2.30473209e-05,  9.81406962e-01]])

In [14]:
d_brickwall = hc.distance_from_plane_to_camera(n_brickwall, np.array([[-1],
                                                                   [-1],
                                                                   [0]], dtype=float), c_r)
d_brickwall

array([[9.3214]])

d_brickwall means the distance between the camera 1 and the plane

In [15]:
q_brickwall_T = n_brickwall.T @ np.linalg.inv(rotation_R.T) @ np.linalg.inv(K_small) / d_brickwall
q_brickwall_T


array([[-2.05716769e-05, -1.42716107e-05,  1.11526634e-01]])

In [16]:
recalculate_H_brick = H_infty + e @ q_brickwall_T  
recalculate_H_brick

array([[ 1.05717936e+00,  3.80694012e-02, -4.45336219e+02],
       [-1.74268711e-02,  9.78760374e-01,  2.47787708e+02],
       [ 2.65056741e-05, -2.30447655e-05,  9.81386992e-01]])

But when I warp the image with this homography, the result is not right. I have focused on it the whole day. But I can't find the reason.

